# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: slack-tw-weather

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  environment:
    CWB_API_KEY: ${env:CWB_API_KEY}
    RADAR_TOPIC_SNS_ARN:
      Fn::Join:
      - ""
      - - "arn:aws:sns:"
        - Ref: "AWS::Region"
        - ":"
        - Ref: "AWS::AccountId"
        - ":radarTopic"

  # you can overwrite defaults here
  #  stage: dev
  region: ap-northeast-1

package:
  exclude:
  - ./**
  include:
  - ./bin/**

functions:
  app:
    handler: bin/weather
    events:
    - http:
        path: weather
        method: post
  funcRadar:
    handler: bin/funcRadar
    events:
    - sns: radarTopic
