# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: slack-tw-weather

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x

# you can overwrite defaults here
#  stage: dev
  region: ap-northeast-1

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  app:
    handler: bin/weather
    events:
      - http:
          path: weather
          method: post
